services:
  stockhive:
    # image: michaeltio/stockhive:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockhive-app
    ports:
      - '5000:5000'
    environment:
      - APP_PORT=5000
      - JWT_SECRET_ACCESS=secret
      - JWT_SECRET_REFRESH=secret
      - DATABASE_URL=postgresql://postgres:root@postgres:5432/invosync_db?schema=public
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: invosync_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
